flowchart LR
    subgraph sg_t0["$$t_{0}$$"]
        t0["$$\text{revision }_0$$"]
    end
    subgraph sg_t1["$$t_{1}$$"]
        t1["$$\text{revision }_1$$"]
    end
    subgraph sg_ts["$$t_{s}$$"]
        ts["..."]
    end
    sg_t0 --> sg_t1 --> sg_ts
